export const AUTH_USER = 'AUTH_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const SET_ROLE_PER_PATH= 'SET_ROLE_PER_PATH';
export const CATALOGUE_LIST= 'CATALOGUE_LIST';
export const PUSH_LIST= 'PUSH_LIST';
export const RESET= 'RESET';
export const ZONE= 'ZONE';
export const RESET_ZONE='RESET_ZONE';
export const PROVINCE='PROVINCE';
export const RESET_PROVINCE='RESET_PROVINCE';
export const CITY= 'CITY';
export const RESET_CITY= 'RESET_CITY';
export const CATEGORY='CATEGORY';
export const RESET_CATEGORY='RESET_CATEGORY';
export const LINE = 'LINE';
export const RESET_LINE = 'RESET_LINE';
export const LIST_BUSINESS_MEN = 'LIST_BUSINESS_MEN';
export const RESET_BUSINESS_MEN = 'RESET_BUSINESS_MEN';
export const RESET_AUTH_USER = 'RESET_AUTH_USER'